In [1]:
import pandas as pd

In [2]:
# Запишем считанные файлы в переменные df (список компаниий) и inn (список ИНН нужных компаний)
df = pd.read_excel('4_inn.xls')
inn = pd.read_csv('4_necessary_inn.txt', header=None)

In [3]:
# Переведем даатфрейм в список через метод .to_list()
list_of_inn = inn[0].to_list()
list_of_inn

[394609645484,
 281578625230,
 923769811917,
 998694734508,
 271011690615,
 924952812367,
 646685244561,
 581531230312,
 841967395801,
 962179889311,
 873191383820,
 590538076039,
 194319975048,
 614658394086,
 571270160555,
 609400911893,
 595260069852,
 706966142477,
 173050718969,
 968048428696,
 806967744814,
 575198252501,
 283081417246,
 663119569897,
 600958529354,
 280452832937,
 415557497037,
 195142638722,
 472181033836,
 722903871682,
 442387408954,
 196518820495,
 653798670054,
 126259856639,
 175482780898,
 192518356612,
 817648134701,
 321724220657,
 864970037680,
 822991191528,
 205472219644,
 532801459453,
 657038381012,
 197916669463,
 849814898285,
 617082656257,
 500480544925,
 765833725639,
 263518962896,
 415856290529,
 812729265571,
 688172366656,
 837771137752,
 456294893364,
 668157292633,
 491435460276,
 323896131459,
 664667769879,
 293128896936,
 833493884251,
 120708914823,
 860475372268,
 172328288163,
 452188261986,
 818829342640,
 948029225406,
 310163740295,
 973834903297,
 499074920916,
 124852843647,
 172587252836,
 270813334693,
 696676566941,
 299222521497,
 682181592872,
 599455346647,
 429358855495,
 607756744365,
 301872309187,
 377093087035,
 157426408379,
 915717036011,
 336147486322,
 725452097724,
 391753469823,
 111910860945,
 430987130018,
 597922572504,
 879473672756,
 424269684543,
 544509469640,
 728283180187,
 149255676155,
 246181878243,
 641538282011,
 666673563650,
 935815591544,
 782372718125,
 897420523262,
 871503698182,
 766327301251,
 581865132298,
 703895742672,
 683933366928,
 884977586630,
 391131415604,
 500226023773,
 776902992723,
 798315862776,
 829796290544,
 664306216794,
 991951385204,
 129413497752,
 447901012904,
 634037614688]

In [4]:
# Отмеберм нужные нам компании через метожд query
df_companies = df.query('head_inn in @list_of_inn')

In [5]:
# Считаем сумму доходов отфильтрованных компаний
df_companies['income,RUB'].sum()

6104522627393